services:
  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/html
    ports:
      - "${NGINX_PORT}:80"
      - "443:443"
    restart: always
    depends_on:
      - php
    networks:
      - bot-network

  mysql:
    build:
      context: ./config/mysql
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./storage/mysql:/var/lib/mysql
    networks:
      - bot-network

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    restart: always
    depends_on:
      - mysql
    networks:
      - bot-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 700M
    ports:
      - "${MY_ADMIN_PORT}:80"
    depends_on:
      - mysql
    networks:
      - bot-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/html
    entrypoint: >
      sh -c "certbot certonly --webroot -w /var/www/html
      --email you@example.com
      -d yourdomen.ru 
      --agree-tos --non-interactive"
    depends_on:
      - nginx

networks:
  bot-network:
    driver: bridge